Algoritmo "Consumo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/06/2025
Var
// Seção de Declarações das variáveis 
 distanciaPercorrida:inteiro
 combustivel, consumoMedio:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Escreva a distância percorrida: ")
 leia(distanciaPercorrida)
 
 escreva("Escreva quanto de combustivel usou: ")
 leia(combustivel)
 
 
consumoMedio<- distanciaPercorrida / combustivel

escreval("Consumo medio é: ", consumoMedio:4:3)

Fimalgoritmo