Algoritmo "crescente "
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/07/2025
Var
// Seção de Declarações das variáveis
x, y, ordem:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite dois numeros: ")
leia(x)
leia(y)

enquanto x <> y faca

            se x < y entao
                escreval("Crescente")
             senao
                escreval("Decrescente")
                fimse
                
             escreval("Digite dois numeros: ")
             leia(x)
             leia(y)
             fimenquanto




Fimalgoritmo
