Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/06/2025
Var
// Seção de Declarações das variáveis 
hora : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite uma hora: ")
leia(hora)

   se hora < 12 entao
      escreval("bom dia")
   senao
        se hora < 18 entao
           escreval("boa tarde")
        senao
           escreval("boa noite")
   fimse
   fimse

Fimalgoritmo

