Algoritmo "estruras"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/07/2025
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

estrutura


enquanto condicao faca

fimenquanto

para variavel de valor_inicial ate valor_final faca

fimpara

se condicao entao

senao

fimse

escolha variavel (opcao)

caso 1

fimescolha


enquanto x < 10 faca
    escreva("Valor de x: ", x)
    x <- x + 1
fimenquanto

para i de 1 ate 5 faca
    escreva("Valor de i: ", i)
fimpara

se x > 5 entao
    escreva("x é maior que 5")
senao
    escreva("x é menor ou igual a 5")
fimse

escolha opcao
    caso 1
        escreva("Opção 1 escolhida")
    caso 2
        escreva("Opção 2 escolhida")
    outrocaso
        escreva("Nenhuma opção válida")
fimescolha



Fimalgoritmo