Algoritmo "fatorial"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/07/2025
Var
// Seção de Declarações das variáveis 
i, N, fatorial: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o valor de N: ")
leia(N)

fatorial<- 1
para i de 1 ate N faca

fatorial<- fatorial * i

fimpara
escreva("FATORIAL = ", fatorial)

Fimalgoritmo

Problema "fatorial" (adaptado de URI 1153)
Fazer um programa para ler um número natural N (valor máximo: 15), e depois calcular e mostrar o
fatorial de N.
Exemplo 1:
Digite o valor de N: 4
FATORIAL = 24
Exemplo 2:
Digite o valor de N: 0
FATORIAL = 1
Exemplo 3:
Digite o valor de N: 6
FATORIAL = 720
Exemplo 4:
Digite o valor de N: 1
FATORIAL = 1