Algoritmo "Idades"

Var

 nome1, nome2: caracter
 idade1, idade2: inteiro
 media: real

Inicio
escreval("Dados da primeira pessoa:")
escreva("nome: ")
leia(nome1)
escreva("idade: ")
leia(idade1)

escreval("Dados da segunda pessoa:")
escreva("nome: ")
leia(nome2)
escreva("idade: ")
leia(idade2)

media <- (idade1 + idade2) / 2
escreval ("A media das idades de ", nome1, " e ", nome2, " é ", media, " anos")



Fimalgoritmo