Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/06/2025
Var
// Seção de Declarações das variáveis 
A, B, C, areaQuadrado, areaTriangulo, areaTrapezio:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a medida A: ")
leia(A)
escreva("Digite a medida B: ")
leia(B)
escreva("Digite a medida C: ")
leia(C)

areaQuadrado<- A * A
areaTriangulo<- A * B
areaTrapezio<- (A + B)*C/2

escreval("AREA DO QUADRADO: ", areaQuadrado:4:2)
escreval("AREA DO TRIANGULO: ", areaTriangulo:4:2)
escreval("AREA DO TRAPEZIO: ", areaTrapezio:4:2)

Fimalgoritmo