Algoritmo "multiplos"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/07/2025
Var
// Seção de Declarações das variáveis 
n1,n2:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite dois numeros inteiros: ")
leia(n1)
leia(n2)

se (n1 % n2 = 0) ou (n2 % n1 = 0) entao

escreval("Sao multiplos")
senao

escreval("Não são multiplos")
fimse



Fimalgoritmo