Algoritmo "Notas"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/06/2025
Var
// Seção de Declarações das variáveis 
nota1, nota2, notaFinal : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Digite a primeira nota: ")
leia(nota1)
escreva("Digite a segunda nota: ")
leia(nota2)

notaFinal <- nota1 + nota2


   escreval("NOTA FINAL = ", notaFinal:4:1)
   
     se(notaFinal < 60) então
             escreval("REPROVADO")
   fimse
   fimse

Fimalgoritmo

