Algoritmo "Salario"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/06/2025
Var
// Seção de Declarações das variáveis 
nome: caractere
pagamento, valorHora: real
horaTrabalhada: inteiro




Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Nome: ", nome)
leia(nome)
escreva("Valor por Hora: ", valorHora)
leia(valorHora)
Escreva("Horas trabalhadas: ", horaTrabalhada)
leia(horaTrabalhada)


 pagamento<- valorHora * horaTrabalhada
 
 escreva("O pagamento de: ", nome,  " é", pagamento:8:3)
Fimalgoritmo