Algoritmo "senha_fixa"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/07/2025
Var
// Seção de Declarações das variáveis 
senha : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Digite sua senha: ")
leia(senha)

enquanto senha <> 2002 faca

escreva("Senha Invalida! Tente novamente: ")
leia(senha)
           fimenquanto
           
           escreva("Acesso permitido!")


Fimalgoritmo