Algoritmo "tabuada"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/07/2025
Var
// Seção de Declarações das variáveis 
N, i, produto: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Deseja a tabuada para qual valor?")
leia(N)

para  i de 1 ate 10 faca

produto<- N * i
escreval(N, " x ", i, " = ", produto)


fimpara


Fimalgoritmo