Algoritmo "Teste_enquanto"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/07/2025
Var
// Seção de Declarações das variáveis
x, soma:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Digite o primeiro numero: ")
leia(x)
soma<- 0
enquanto x <> 0 faca
soma<- x + soma
escreva ("Digite outro numero: ")
leia(x)

fimenquanto
escreval("Soma = ", soma)



Fimalgoritmo