Algoritmo "treino_vetor"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/07/2025
Var
// Seção de Declarações das variáveis 

idade, N, i : inteiro
vet: vetor [0..9] de inteiro
vet2: vetor [0..9] de caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
idade<- 0
   escreval("QUANTOS CADASTROS")
   leia(N)

     para i de 0 até N-1 faca
     escreva("Digite seu nome: ")
     leia(vet2[i])
     escreva("Digite sua idade: ")
     leia(vet[i])
     
     
     fimpara
     
     
     escreval
     
     
     para i de 0 ate N-1 faca
     escreval("nome: ", vet2[i]," idade: ", vet[i])
     //escreval(vet[i])
     
     fimpara






Fimalgoritmo