Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/07/2025
Var
// Seção de Declarações das variáveis 

n1, n2, media: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a primeira nota: ")
leia(n1)



enquanto (n1 < 0) ou (n1 > 10) faca

         escreva("Valor invalido! Tente novamente: ")
         leia(n1)



fimenquanto

         escreva("Digite a segunda nota: ")
         leia(n2)

enquanto (n2 < 0) ou (n2 > 10) faca
         escreva("Valor invalido! Tente novamente: ")
         leia(n2)

fimenquanto
         media<- (n1 + n2)/2
         escreva("MEDIA = ", media:4:2)

           
           



Fimalgoritmo